### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by timothybennette8** [Hennamann/CC-Extension-Builder-For-Visual-Studio-Code#18]
Hi there!
I'm super keen to use this extension, but I can't for the life of me figure out the usage to scaffolding a new CC Extension within VSCode. Where would I find the documentation to do so?
Thanks!
Tim

**Comment by timothybennette8** [comment]
I've found the documentation and I've been poking around the repo and it looks like node.js? 
I tried running `createext.bat templatename extid` in the root of a new project (like, just an empty folder, no npm init or anything like that), but unsurprisingly it returned the .bat as unrecognised.
Do I need to build a node app first? Or is this just because it's going to create a node panel/app? I feel like I'm missing something key.
Please forgive my novice coder knowledge here!

**Comment by Hennamann** [comment]
Hi,

The bat files are the underlying files used to generate the extension files you should not need to use them by themselves.

The extension works using the Command system in vscode. Cmd/Ctrl+shift+p and type extension into the field. It should bring up two commands, one for enabling CEP debug mode, which is required to test extensions without signing them first.
The other command generates the extension files and puts them in the correct location for the Adobe host apps to fins and load it, after asking you a few questions. 

Hope this helps explaining it further. If i find the time i might update the readme file with a more detailed instruction.

**Comment by timothybennette8** [comment]
Amazing, thank you! 
I knew I was missing something simple!
