### ISSUE TITLE
Debug extension

### ISSUE THREAD

**Issue by sandroweb** [Hennamann/CC-Extension-Builder-For-Visual-Studio-Code#2]
How I can run my created extension?

**Comment by Hennamann** [comment]
If you have enabled debug mode on your machine (This can be done by using the "enable debug mode" command added by this extension.) You should be able to find your extension in whatever Adobe app you specified support for in the extension manifest file.

**Comment by Hennamann** [comment]
I assume this issue has been solved. Closing
