### ISSUE TITLE
Thank you for creating a documentation for this extension (!)

### ISSUE THREAD

**Issue by zeybek** [Hennamann/CC-Extension-Builder-For-Visual-Studio-Code#4]
How can we start debugging ?

**Comment by Hennamann** [comment]
This extension does not offer debugging from within Visual Studio code, it only allows for easier project creation and managing. To debug your extension you would do as normal using the Chrome web browser, for more info check the official CEP cookbook: https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md
