### ISSUE TITLE
Suggestion: Adding prefix for this vscode extension 

### ISSUE THREAD

**Issue by takato1314** [Hennamann/CC-Extension-Builder-For-Visual-Studio-Code#5]
Hi, thank you for the library.

It would be nice if there's a prefix added just to sort out the functionalities of this extensions with all other installed extensions in VSCode.

Expected outcome: Take for example, the [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) extension:
 
![image](https://user-images.githubusercontent.com/10910968/53360217-f10fac00-396f-11e9-93f3-467c3c20500d.png)

**Comment by Hennamann** [comment]
That's a great idea! I'll get that implemented asap! 👍🏻
