### ISSUE TITLE
How does debugging work?

### ISSUE THREAD

**Issue by cabcookie** [Hennamann/CC-Extension-Builder-For-Visual-Studio-Code#6]
I copied the launch.json into my VS Code work folder. When I launch I can see my extension in After Effects. But how can I really debug it? I created a new extension using the topcoat template. I added a second alert message in the hostscript.jsx file and set a breakpoint on it. How can I make this work? Thanks for your advice :-)

**Comment by Hennamann** [comment]
Debugging CEP extensions is done using the chrome devtools found in the Chrome web browser. It sounds to me like you are using the Official Adobe Extendscript debugger extension for VS code, which allows for debugging stand alone extendscript scripts in their host apps, it's not intended for CEP extensions. More info on debugging CEP extensions can be found here: https://github.com/Adobe-CEP/Getting-Started-guides/tree/master/Client-side%20Debugging
