### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by MrDChristop** [Hennamann/CC-Extension-Builder-For-Visual-Studio-Code#8]
Hi
i installed the extension but can not find a way to use it.
Can you explain this a bit more?

Thanks

**Comment by curtney** [comment]
I cannot find any configuration for the extension. A brief explanation how to setup the extension would be great. 

Thanks

**Comment by curtney** [comment]
Okay, I figured it out! 
1. Go to "Command Palette" (View -->Command Palette or simply press F1).
2. type "Extension Creator" You will see the command "Create a New CC Extension" select it and follow the prompts.

> Hi
> i installed the extension but can not find a way to use it.
> Can you explain this a bit more?
> 
> Thanks

**Comment by rupeshbhatti** [comment]
Thanks @curtney ... how does one then access an extension in the desired Adobe CC app e.g. Premiere Pro?

**Comment by rupeshbhatti** [comment]
I've just worked it out. Incase it's of use for anyone else:
1. Go to `Command Palette` (on the mac use cmd-shift-p)
2. Find and select `Extension Creator: Enable CEP Debug mode`

This will activate the extension. Next, open the Adobe CC app and you should see your extension under `window -> extensions`

**Comment by schroef** [comment]
Looks like a great tool indeed, but could some info on that screen :)

Ps does anyone know if i can also debug an already made extension with this tool. I don't really like CEFclient, Chrome devtools don't work properly

<img width="1032" alt="Screen Shot 2020-03-27 at 14 09 37" src="https://user-images.githubusercontent.com/6923008/77786722-a8279c80-7034-11ea-8fc2-17f4394e17fa.png">

**Comment by Hennamann** [comment]
Should have answered here long ago, apologies for that.
I'll get the readme updated with instructions, i guess i just assumed that everyone using VScode were familiar with extensions and the command palette. 

@schroef  Outside of the use of CEFclient or chrome dev tools there really is no good way of debugging CEP extensions. Though you can debug extendscript files using the official Adobe Extendscript Debugger extension from Adobe: https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug 

Adobe is working on a new plugin/extension system called UXP which will improve debugging, but it's currently only available for XD and soon Photoshop. And it's a completely different system from CEP.
